site_name: NFL
theme:
  name: material
docs_dir: docs
nav:
  - Home: index.md
  - Blueprint: blueprint.md
  - Architecture: architecture.md
  - API: api_reference.md
  - Tutorials:
      - Hello World: tutorials/0-hello-world.md
