[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nfl"
version = "0.1.0"
description = "NodeForm Language CLI utilities"
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
nfl = "cli.nfl_cli:main"
