version: "3.8"
services:
  nfl-wasm:
    image: ghcr.io/builtbycorelot/nfl-wasm:latest
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: ["sleep", "infinity"]

  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./results:/data/results

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
