name: CI

on:
  push:

    branches: [main]
  pull_request:
    branches: [main]
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run Python tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: |
          if [ -f package.json ]; then npm install; fi

      - name: Run Node tests with coverage
        run: |
          if [ -f package.json ]; then npm test -- --coverage; fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml,coverage/lcov.info
          fail_ci_if_error: false
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run tests
        run: pytest -v

